#!/usr/bin/env python3
"""Reuse compatible PETSc, or install a pinned official release with this MPI."""
import argparse
import fcntl
import hashlib
import json
import os
from pathlib import Path
import shlex
import shutil
import subprocess
import sys
import tarfile
import urllib.request

from common import BASE, write_json
from petsc_config import discover, preflight, sha256, wrapper_command, output

VERSION = '3.25.5'
URL = 'https://web.cels.anl.gov/projects/petsc/download/release-snapshots/petsc-' + VERSION + '.tar.gz'


def environment_file(path, config):
    """Only PETSc-related variables are exported, never compiler/module overrides."""
    lines = ['# Generated by setup_petsc.py; use the same MPI/compiler modules at build and run.']
    for name in ('PETSC_DIR', 'PETSC_ARCH', 'PKG_CONFIG_PATH'):
        if name in os.environ:
            lines.append('export ' + name + '=' + shlex.quote(os.environ[name]))
        elif name in ('PETSC_DIR', 'PETSC_ARCH'):
            lines.append('unset ' + name)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix('.tmp')
    temporary.write_text('\n'.join(lines) + '\n')
    temporary.replace(path)
    write_json(path.with_suffix('.json'), config)
    print('PETSc ready: ' + config['version'], flush=True)
    print('Environment saved: ' + str(path), flush=True)


def check_existing(compiler):
    config = discover()
    return preflight(config, compiler, True)


def unpack(archive, destination):
    # Avoid tar traversal even for a downloaded source distribution.
    with tarfile.open(str(archive), 'r:gz') as bundle:
        for member in bundle.getmembers():
            target = (destination / member.name).resolve()
            if os.path.commonpath([str(destination.resolve()), str(target)]) != str(destination.resolve()):
                raise RuntimeError('Unsafe source archive path: ' + member.name)
            if member.issym() or member.islnk():
                # PETSc official releases do not need escaping symlinks.
                linked = (target.parent / member.linkname).resolve() if member.issym() else (destination / member.linkname).resolve()
                if os.path.commonpath([str(destination.resolve()), str(linked)]) != str(destination.resolve()):
                    raise RuntimeError('Unsafe source archive link: ' + member.name)
        bundle.extractall(str(destination))


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--install', action='store_true', help='Use a matching private installation even if another PETSc is visible')
    parser.add_argument('--jobs', type=int, default=int(os.environ.get('SLURRY_BUILD_JOBS', os.environ.get('SLURM_CPUS_PER_TASK', '4'))))
    parser.add_argument('--prefix-root', type=Path,
                        default=Path(os.environ.get('SLURRY_PETSC_ROOT', str(Path.home() / '.local/slurry-petsc'))))
    parser.add_argument('--archive', type=Path, help='Use an already downloaded official petsc-3.25.5.tar.gz')
    parser.add_argument('--sha256', help='Optional independently obtained archive SHA256 to verify before extracting')
    args = parser.parse_args(argv)
    if args.jobs < 1:
        parser.error('--jobs must be positive')
    compiler = shutil.which(os.environ.get('SLURRY_CXX', 'mpicxx'))
    ccompiler = shutil.which(os.environ.get('SLURRY_CC', 'mpicc'))
    if not compiler or not ccompiler:
        raise RuntimeError('MPI C/C++ compilers not found. Load the same compiler/MPI modules as build_slurry_cpu.sbatch.')
    envfile = BASE / 'build/petsc/env.sh'
    if not args.install:
        try:
            config = check_existing(compiler)
        except RuntimeError as error:
            # Missing PETSc permits installation. A detected but incompatible
            # installation is an actionable error, not something to hide.
            if 'PETSc not found.' not in str(error):
                raise
        else:
            environment_file(envfile, config)
            return
    identity = {'cxx': compiler, 'cc': ccompiler,
                'wrapper': wrapper_command(compiler), 'version': output([compiler, '--version'])}
    fingerprint = hashlib.sha256(json.dumps(identity, sort_keys=True).encode()).hexdigest()[:12]
    destination = args.prefix_root.expanduser().resolve() / VERSION / fingerprint
    if any(ch.isspace() for ch in str(destination)):
        raise RuntimeError('PETSc installation path must not contain whitespace')
    destination.mkdir(parents=True, exist_ok=True)
    with (destination / 'install.lock').open('a') as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)
        prefix = destination / 'install'
        os.environ['PETSC_DIR'] = str(prefix)
        os.environ.pop('PETSC_ARCH', None)
        if (prefix / 'include/petscconf.h').is_file():
            config = check_existing(compiler)
            environment_file(envfile, config)
            return
        archive = args.archive.expanduser().resolve() if args.archive else destination / ('petsc-' + VERSION + '.tar.gz')
        if not archive.is_file():
            if args.archive:
                raise RuntimeError('Source archive not found: ' + str(archive))
            print('Downloading official PETSc ' + VERSION + ': ' + URL, flush=True)
            temporary = archive.with_suffix('.part')
            urllib.request.urlretrieve(URL, str(temporary))
            temporary.replace(archive)
        archive_hash = sha256(archive)
        if args.sha256 and archive_hash.lower() != args.sha256.lower():
            raise RuntimeError('PETSc source archive SHA256 mismatch')
        source = destination / ('petsc-' + VERSION)
        if not (source / 'configure').is_file():
            unpack(archive, destination)
        if not (source / 'configure').is_file():
            raise RuntimeError('Archive does not contain expected petsc-' + VERSION + '/configure')
        # Do not download another MPI. PETSc and OpenLB must share this MPI.
        configure = [sys.executable, str(source / 'configure'), '--prefix=' + str(prefix),
                     '--with-cc=' + ccompiler, '--with-cxx=' + compiler, '--with-fc=0',
                     '--with-mpi=1', '--with-debugging=0', '--with-shared-libraries=1',
                     '--with-scalar-type=real', '--with-precision=double',
                     '--download-f2cblaslapack=1', 'COPTFLAGS=-O3', 'CXXOPTFLAGS=-O3',
                     'PETSC_ARCH=arch-slurry-opt', '--with-make-np=' + str(args.jobs)]
        clean_env = os.environ.copy()
        clean_env['PETSC_DIR'] = str(source)
        clean_env['PETSC_ARCH'] = 'arch-slurry-opt'
        print('Configuring PETSc with ' + compiler + '; full output below.', flush=True)
        subprocess.run(configure, cwd=str(source), env=clean_env, check=True)
        makevars = ['PETSC_DIR=' + str(source), 'PETSC_ARCH=arch-slurry-opt']
        subprocess.run(['make', '-j' + str(args.jobs)] + makevars + ['all'], cwd=str(source), env=clean_env, check=True)
        subprocess.run(['make'] + makevars + ['install'], cwd=str(source), env=clean_env, check=True)
        config = check_existing(compiler)
        config['installation'] = {'source_url': URL, 'source_archive_sha256': archive_hash,
                                  'configure_command': configure, 'toolchain': identity}
        environment_file(envfile, config)


if __name__ == '__main__':
    try:
        main()
    except (RuntimeError, OSError, subprocess.CalledProcessError) as error:
        print('PETSC SETUP FAILED: ' + str(error), file=sys.stderr)
        sys.exit(1)
