# MIT CPU build: GCC 12.2.0 + OpenMPI 4.1.4.
CXX := mpicxx
CC := gcc
CXXFLAGS := -O3 -Wall -std=c++20
LDFLAGS :=
PARALLEL_MODE := MPI
MPIFLAGS :=
OMPFLAGS := -fopenmp
PLATFORMS := CPU_SISD
FLOATING_POINT_TYPE := double
FEATURES :=
USE_EMBEDDED_DEPENDENCIES := ON
